# -*- coding: utf-8 -*-
"""App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jDe8AAUsCDwbABa8lIjI6HYhablSidlJ
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go

# -----------------------------
# Page config
# -----------------------------
st.set_page_config(
    page_title="Predictive Maintenance Dashboard",
    layout="wide"
)

st.title("🛠️ Predictive Maintenance Dashboard")
st.caption("Health Index, Anomalies & Maintenance Alerts")

# -----------------------------
# Load data
# -----------------------------
@st.cache_data
def load_data():
    # Replace with your processed dataframe source
    df = pd.read_csv("pdm_processed_data.csv")
    return df

df = load_data()

# -----------------------------
# Sidebar
# -----------------------------
st.sidebar.header("Controls")

hi_threshold = st.sidebar.slider(
    "Health Index threshold",
    min_value=0.3,
    max_value=0.8,
    value=0.5,
    step=0.05
)

show_raw_hi = st.sidebar.checkbox("Show raw Health Index", value=False)

# -----------------------------
# KPI Section
# -----------------------------
latest = df.iloc[-1]

col1, col2, col3, col4 = st.columns(4)

col1.metric("Current HI", f"{latest['HI_smooth']:.2f}")
col2.metric("Alert Level", latest["alert_label"])
col3.metric("Anomalies (24h)", int(latest["anomaly_24h_count"]))
col4.metric("Running Hours", int(latest["RUNNING HOURS"]))

# -----------------------------
# Health Index + Anomalies plot
# -----------------------------
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=df["RUNNING HOURS"],
        y=df["HI_smooth"],
        mode="lines",
        name="HI (Smoothed)",
        line=dict(width=3)
    )
)

if show_raw_hi:
    fig.add_trace(
        go.Scatter(
            x=df["RUNNING HOURS"],
            y=df["Health_Index"],
            mode="lines",
            name="HI (Raw)",
            opacity=0.4
        )
    )

# Anomalies
anomaly_df = df[df["anomaly"] == 1]

fig.add_trace(
    go.Scatter(
        x=anomaly_df["RUNNING HOURS"],
        y=anomaly_df["HI_smooth"],
        mode="markers",
        name="Anomalies",
        marker=dict(size=7, color="orange")
    )
)

# Thresholds
fig.add_hline(y=0.7, line_dash="dash", line_color="green", annotation_text="Healthy")
fig.add_hline(y=0.5, line_dash="dash", line_color="orange", annotation_text="Warning")
fig.add_hline(y=0.4, line_dash="dash", line_color="red", annotation_text="Critical")

fig.update_layout(
    height=450,
    xaxis_title="Running Hours",
    yaxis_title="Health Index",
    legend=dict(orientation="h", y=-0.2)
)

st.plotly_chart(fig, use_container_width=True)

# -----------------------------
# Alert banner
# -----------------------------
st.subheader("🚦 Maintenance Alert Status")

if latest["alert_level"] == 0:
    st.success("System operating normally.")
elif latest["alert_level"] == 1:
    st.warning("Early degradation detected. Increase monitoring.")
elif latest["alert_level"] == 2:
    st.error("WARNING: Schedule maintenance inspection.")
else:
    st.error("CRITICAL: Immediate maintenance required!")

# -----------------------------
# Recent anomalies table
# -----------------------------
st.subheader("📋 Recent Anomalies (Last 48 Hours)")

recent_anomalies = df.tail(48)
recent_anomalies = recent_anomalies[recent_anomalies["anomaly"] == 1]

st.dataframe(
    recent_anomalies[
        [
            "RUNNING HOURS",
            "HI_smooth",
            "anomaly_24h_count",
            "alert_label"
        ]
    ],
    use_container_width=True
)

# -----------------------------
# Footer
# -----------------------------
st.caption("PdM system powered by Physics-Informed Features + Isolation Forest")