# -*- coding: utf-8 -*-
"""RCL 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nCo7lyBRtesfblD_-qOOEypvKLM_3obG
"""

import pandas as pd
import numpy as np

# Load data
df = pd.read_excel("/content/merged_gg4_logs.xlsx")

# Quick inspection
df.head(), df.shape

df.info()

for col in df.select_dtypes(include='object').columns:
    if col != 'Date': # 'Date' column is already datetime and should not be converted to float
        df[col] = pd.to_numeric(df[col], errors='coerce')

# Convert all numeric columns to float64 for consistency where possible
for col in df.select_dtypes(include=['int64', 'float64']).columns:
    df[col] = df[col].astype('float64')

df.info()

# Drop rows with too many missing values
df = df.dropna(thresh=int(0.8 * df.shape[1]))

# Set 'Date' column as index for time-based interpolation
df = df.set_index('Date')

# Interpolate gently
df = df.interpolate(method="time", limit=5)

df.isna().sum()

df = df.drop(columns=['EXHAUST TEMPERATURE B-BANK', 'THROTTLE POSITION B-BANK'])
df.isna().sum()

df.info()

pdm_features = [
    # Load & speed
    "LOAD (kW)", "RPM", "FREQUENCY",

    # Electrical stability
    "VOLTAGE", "POWER FACTOR", "CURRENT (AMP)",

    # Combustion
    "EXHAUST TEMPERATURE A-BANK",
    "THROTTLE POSITION A-BANK",
    "GAS MIXER STEPS",
    "GAS PRESSURE. KG/Cm2",

    # Cooling (HT & LT)
    "HT INLET TEMPERATURE",
    "HT OUTLET TEMPERATURE",
    "LT INLET TEMPERATURE",
    "HT 3 WAY VALVE OPENING %",
    "LT 3 WAY VALVE OPENING %",
    "BEFORE HT PUMP PRESSURE",
    "AFTER HT PUMP PRESSURE",
    "BEFORE LT PUMP PRESSURE",
    "AFTER LT PUMP PRESSURE",

    # Aging
    "RUNNING HOURS"
]

# Corrected column name from 'timestamp' to 'Date'
# Also, reset the index to make 'Date' a regular column again before selecting
df_pdm = df.reset_index()[["Date"] + pdm_features].dropna()

# Correlations with Load
print("\nTop 10 Correlations with LOAD (kW):")
corr_load = df_pdm.corr()['LOAD (kW)'].sort_values(ascending=False)
print(corr_load)

# Step 10: Sample data for plotting (every 20th point to keep charts light)
sample_idx = np.arange(0, len(df), 20)
df_sample = df.iloc[sample_idx]

import matplotlib.pyplot as plt
plt.figure(figsize=(12, 6))
plt.plot(df_pdm['Date'], df_pdm['LOAD (kW)'], label='Load (kW)')
plt.xlabel('Date')
plt.ylabel('Load (kW)')
plt.title('Load Trend over TIme')
plt.grid(True)
plt.show()

plt.figure(figsize=(12, 6))
plt.plot(df_pdm['Date'], df['LUBE OIL TEMPERATURE'], color='red')
plt.xlabel('Date')
plt.ylabel('Lube Oil Temperature (°C)')
plt.title('Lube Oil Temperature Trend')
plt.grid(True)
plt.show()

df.describe()

import plotly.express as px

winding_cols = ['WINDING TEMP. U', 'WINDING TEMP. V', 'WINDING TEMP. W']

temp_cols = winding_cols

# Prepare data for plotting multiple series
df_temp_plot = df[temp_cols].reset_index().melt(id_vars=['Date'], var_name='Temperature Type', value_name='Temperature (C)')

fig = px.line(df_temp_plot, x='Date', y='Temperature (C)', color='Temperature Type',
              title='Winding and Bearing Temperatures over Time',
              labels={'Date': 'Date', 'Temperature (C)': 'Temperature (°C)'})

fig.update_layout(hovermode="x unified")
fig.show()

import plotly.express as px

combustion_cols = ['AVG. COMBUSTION TEMP. (A bANK)', 'AVG. COMBUSTION TEMP. (B bANK)']

# Prepare data for plotting multiple series
df_combustion_plot = df[combustion_cols].reset_index().melt(id_vars=['Date'], var_name='Combustion Temperature Type', value_name='Temperature (C)')

fig = px.line(df_combustion_plot, x='Date', y='Temperature (C)', color='Combustion Temperature Type',
              title='Combustion Temperatures over Time',
              labels={'Date': 'Date', 'Temperature (C)': 'Temperature (°C)'})

fig.update_layout(hovermode="x unified")
fig.show()

def engineer_pdm_features(
    df: pd.DataFrame,
    rolling_window: int = 10,
    time_col: str = "timestamp"
) -> pd.DataFrame:
    """
    Engineer physics-informed features for Predictive Maintenance (PdM)
    on gas engine generator data.

    Parameters
    ----------
    df : pd.DataFrame
        Cleaned dataframe containing raw sensor data and timestamp.
    rolling_window : int, optional
        Window size (in hours) for rolling statistics.
    time_col : str, optional
        Name of timestamp column.

    Returns
    -------
    pd.DataFrame
        DataFrame with engineered PdM features.
    """

    df = df.copy()
    df = df.sort_values(time_col).reset_index(drop=True)

    # -------------------------------------------------
    # 1. Thermal & Cooling Health
    # -------------------------------------------------
    df["HT_delta_T"] = (
        df["HT OUTLET TEMPERATURE"] - df["HT INLET TEMPERATURE"]
    )

    df["HT_stress"] = (
        df["HT OUTLET TEMPERATURE"] / df["LOAD (kW)"]
    )

    df["Cooling_efficiency"] = (
        df["HT_delta_T"] / df["HT 3 WAY VALVE OPENING %"]
    )

    # -------------------------------------------------
    # 2. Combustion Health (Single-Bank)
    # -------------------------------------------------
    df["Exhaust_stress"] = (
        df["EXHAUST TEMPERATURE A-BANK"] / df["LOAD (kW)"]
    )

    df["Throttle_stress"] = (
        df["THROTTLE POSITION A-BANK"] / df["LOAD (kW)"]
    )

    df["Gas_utilization_index"] = (
        df["LOAD (kW)"] / df["GAS PRESSURE. KG/Cm2"]
    )

    # -------------------------------------------------
    # 3. Pump & Hydraulic Health
    # -------------------------------------------------
    df["HT_pump_delta_P"] = (
        df["AFTER HT PUMP PRESSURE"] - df["BEFORE HT PUMP PRESSURE"]
    )

    df["LT_pump_delta_P"] = (
        df["AFTER LT PUMP PRESSURE"] - df["BEFORE LT PUMP PRESSURE"]
    )

    # -------------------------------------------------
    # 4. Electrical & Mechanical Consistency
    # -------------------------------------------------
    df["Power_estimated"] = (
        np.sqrt(3)
        * df["VOLTAGE"]
        * df["CURRENT (AMP)"]
        * df["POWER FACTOR"]
        / 1000  # convert W → kW
    )

    df["Power_error"] = (
        df["Power_estimated"] - df["LOAD (kW)"]
    )

    # -------------------------------------------------
    # 5. Time-Series Stability & Degradation
    # -------------------------------------------------
    df["HT_outlet_roll_mean"] = (
        df["HT OUTLET TEMPERATURE"]
        .rolling(rolling_window)
        .mean()
    )

    df["RPM_roll_std"] = (
        df["RPM"]
        .rolling(rolling_window)
        .std()
    )

    df["Frequency_roll_std"] = (
        df["FREQUENCY"]
        .rolling(rolling_window)
        .std()
    )

    # -------------------------------------------------
    # 6. Aging & Efficiency Loss
    # -------------------------------------------------
    df["Load_per_running_hour"] = (
        df["LOAD (kW)"] / df["RUNNING HOURS"]
    )

    # Thermal drift rate (slope approximation)
    df["Thermal_drift_rate"] = (
        df["HT OUTLET TEMPERATURE"]
        .diff() / df[time_col].diff().dt.total_seconds()
    )


    # 7. Final Cleanup
    # Drop 'Date' and 'TIME' columns if they exist. 'errors='ignore' prevents KeyError if they don't.
    df = df.drop(columns=[time_col, "TIME"], errors='ignore')
    df = df.replace([np.inf, -np.inf], np.nan)
    df = df.dropna().reset_index(drop=True)

    return df

df_pdm = engineer_pdm_features(
    df=df.reset_index(),  # Reset the index to make 'Date' a regular column
    rolling_window=10,
    time_col='Date'       # Specify the correct name of the time column
)

df_pdm.info()

engineered_features = [
    "HT_delta_T",
    "HT_stress",
    "Cooling_efficiency",
    "Exhaust_stress",
    "Throttle_stress",
    "Gas_utilization_index",
    "HT_pump_delta_P",
    "LT_pump_delta_P",
    "Power_estimated",
    "Power_error",
    "HT_outlet_roll_mean",
    "RPM_roll_std",
    "Frequency_roll_std",
    "Load_per_running_hour",
    "Thermal_drift_rate"
]

thermal_mech_features = [
    "BEARING TEMP. A",
    "BEARING TEMP. B",
    "WINDING TEMP. U",
    "WINDING TEMP. V",
    "WINDING TEMP. W",
    "LUBE OIL TEMPERATURE",
    "CRANKCASE PRESSURE",
    "HT INLET TEMPERATURE",
    "HT OUTLET TEMPERATURE",
    "LT INLET TEMPERATURE"
]

electrical_features = [
    "LOAD (kW)",
    "VOLTAGE",
    "CURRENT (AMP)",
    "POWER FACTOR",
    "RPM",
    "FREQUENCY"
]



# Correlation for thermal_mech_features
features = thermal_mech_features

# Compute Pearson correlation
corr = df[features].corr()

# Mask upper triangle
corr_masked = corr.copy()
corr_masked.values[np.triu_indices_from(corr_masked)] = np.nan

# Plot
plt.figure(figsize=(12, 10))
plt.imshow(corr_masked, vmin=-1, vmax=1, cmap='coolwarm')
plt.colorbar(label='Pearson Correlation Coefficient')

plt.xticks(range(len(features)), features, rotation=90)
plt.yticks(range(len(features)), features)

# Add numbers to the lower triangle
for i in range(len(features)):
    for j in range(i + 1):
        if not pd.isna(corr_masked.iloc[i, j]):
            plt.text(j, i, f"{corr_masked.iloc[i, j]:.2f}",
                     ha="center", va="center", fontsize=8, color='black')

plt.title("Pearson Correlation – Thermal & Mechanical Features")
plt.tight_layout()
plt.show()

# Correlation for electrical_features
features = electrical_features

# Compute Pearson correlation
corr = df[features].corr()

# Mask upper triangle
corr_masked = corr.copy()
corr_masked.values[np.triu_indices_from(corr_masked)] = np.nan

# Plot
plt.figure(figsize=(10, 8))
plt.imshow(corr_masked, vmin=-1, vmax=1, cmap='coolwarm')
plt.colorbar(label='Pearson Correlation Coefficient')

plt.xticks(range(len(features)), features, rotation=90)
plt.yticks(range(len(features)), features)

# Add numbers to the lower triangle
for i in range(len(features)):
    for j in range(i + 1):
        if not pd.isna(corr_masked.iloc[i, j]):
            plt.text(j, i, f"{corr_masked.iloc[i, j]:.2f}",
                     ha="center", va="center", fontsize=8, color='black')

plt.title("Pearson Correlation – Electrical Features")
plt.tight_layout()
plt.show()



import seaborn as sns

df_corr = df_pdm[engineered_features].copy()

corr_matrix = df_corr.corr(method="pearson")

# Create a mask for the upper triangle
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))

plt.figure(figsize=(14, 12))
sns.heatmap(corr_matrix, mask=mask, annot=True, fmt=".2f", cmap='coolwarm',
            cbar_kws={'label': 'Pearson Correlation Coefficient'},
            linewidths=.5, linecolor='lightgrey', center=0)

plt.title(
    "Pearson Correlation – Engineered PdM Features",
    pad=20
)
plt.xticks(rotation=90, ha='center')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

# Correlation for engineered_features
features = engineered_features

# Compute Pearson correlation
corr = df_pdm[features].corr()

# Mask upper triangle
corr_masked = corr.copy()
corr_masked.values[np.triu_indices_from(corr_masked)] = np.nan

# Plot
plt.figure(figsize=(14, 12))
plt.imshow(corr_masked, vmin=-1, vmax=1, cmap='coolwarm')
plt.colorbar(label='Pearson Correlation Coefficient')

plt.xticks(range(len(features)), features, rotation=90)
plt.yticks(range(len(features)), features)

# Add numbers to the lower triangle
for i in range(len(features)):
    for j in range(i + 1):
        if not pd.isna(corr_masked.iloc[i, j]):
            plt.text(j, i, f"{corr_masked.iloc[i, j]:.2f}",
                     ha="center", va="center", fontsize=8, color='black')

plt.title("Pearson Correlation – Engineered PdM Features")
plt.tight_layout()
plt.show()

# -----------------------------
# Feature groups
# -----------------------------

LOAD_FEATURES = [
    "LOAD (kW)",
    "ACTUAL POWER (%)",
    "Power_estimated",
    "Power_error",
    "Load_per_running_hour"
]

THERMAL_FEATURES = [
    "BEARING TEMP. A",
    "BEARING TEMP. B",
    "WINDING TEMP. U",
    "WINDING TEMP. V",
    "WINDING TEMP. W",
    "AVG. COMBUSTION TEMP. (A bANK)",
    "AVG. COMBUSTION TEMP. (B bANK)",
    "EXHAUST TEMPERATURE A-BANK",
    "HT_delta_T",
    "Thermal_drift_rate"
]

COOLING_FEATURES = [
    "HT INLET TEMPERATURE",
    "HT OUTLET TEMPERATURE",
    "LT INLET TEMPERATURE",
    "Cooling_efficiency",
    "HT_stress"
]

MECHANICAL_FEATURES = [
    "RPM",
    "RPM_roll_std",
    "Frequency_roll_std",
    "CRANKCASE PRESSURE"
]

LUBRICATION_FEATURES = [
    "LUBE OIL TEMPERATURE",
    "LUBE OIL PRESSURE",
    "LUBE OIL LEVEL"
]

GAS_COMBUSTION_FEATURES = [
    "GAS PRESSURE. KG/Cm2",
    "Gas_utilization_index",
    "Exhaust_stress",
    "Throttle_stress"
]

ELECTRICAL_FEATURES = [
    "VOLTAGE",
    "CURRENT (AMP)",
    "POWER FACTOR",
    "FREQUENCY"
]

# -----------------------------
# Final feature set
# -----------------------------
SELECTED_FEATURES = (
    LOAD_FEATURES +
    THERMAL_FEATURES +
    COOLING_FEATURES +
    MECHANICAL_FEATURES +
    LUBRICATION_FEATURES +
    GAS_COMBUSTION_FEATURES +
    ELECTRICAL_FEATURES
)

# Corrected: Select features from df_pdm instead of df
df = df_pdm[["RUNNING HOURS"] + SELECTED_FEATURES]

from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import IsolationForest

scaler = MinMaxScaler()

scaled_features = scaler.fit_transform(df[SELECTED_FEATURES])

df_scaled = pd.DataFrame(
    scaled_features,
    columns=SELECTED_FEATURES,
    index=df.index
)

df["Health_Index"] = 1 - df_scaled.mean(axis=1)

df["HI_smooth"] = (
    df["Health_Index"]
    .rolling(window=24, min_periods=6)
    .mean()
)

ANOMALY_FEATURES = [
    "HT_delta_T",
    "Cooling_efficiency",
    "Exhaust_stress",
    "RPM_roll_std",
    "Power_error",
    "Thermal_drift_rate"
]

iso = IsolationForest(
    n_estimators=200,
    contamination=0.05,
    random_state=42
)

df["anomaly"] = iso.fit_predict(df[ANOMALY_FEATURES])
df["anomaly"] = (df["anomaly"] == -1).astype(int)

df["anomaly_24h_count"] = (
    df["anomaly"]
    .rolling(window=24, min_periods=6)
    .sum()
)

def maintenance_alert_logic(df):
    conditions = [
        (df["HI_smooth"] > 0.7),
        ((df["HI_smooth"] <= 0.7) & (df["HI_smooth"] > 0.5)),
        ((df["HI_smooth"] <= 0.5) & (df["anomaly_24h_count"] >= 3)),
        ((df["HI_smooth"] <= 0.4) & (df["anomaly_24h_count"] >= 5))
    ]

    alert_levels = [0, 1, 2, 3]

    df["alert_level"] = np.select(conditions, alert_levels, default=1)
    return df

df = maintenance_alert_logic(df)

alert_map = {
    0: "Normal",
    1: "Watch",
    2: "Warning",
    3: "Critical"
}

df["alert_label"] = df["alert_level"].map(alert_map)

